In [2]:
import pandas as pd
from pathlib import Path

In [ ]:
DATA_DIR = Path("../data/raw/")

In [4]:
df

,id,user_id,text,timestamp,bot_flag,via_bot_id,via_business_bot_id,reply_to_msg_id,fwd_flag,fwd_from_id,media_type,views,forwards,replies,reactions,reaction_json,file_path,group_name
0,162992,NaN,A 6.6 magnitude earthquake is recorded off the...,1.698797e+09,None,NaN,NaN,NaN,None,1.752949e+09,MessageMediaDocument,1331.0,4.0,0.0,10.0,"{""\ud83d\ude31"": 7, ""\ud83d\ude4f"": 2, ""\u2764...",file:///home/students/moliveira/telegram_2024/...,channel_1469309761
1,162993,1.229970e+09,IDF choppering in troops that are dead or inju...,1.698797e+09,None,NaN,NaN,NaN,None,1.884130e+09,MessageMediaDocument,12588.0,163.0,1.0,0.0,null,file:///home/students/moliveira/telegram_2024/...,channel_1469309761
2,162994,1.586867e+09,"Suppose to take months, no surprise it's not e...",1.698797e+09,None,NaN,NaN,162993.0,None,NaN,NaN,NaN,NaN,0.0,0.0,null,file:///home/students/moliveira/telegram_2024/...,channel_1469309761
3,162995,NaN,Ex-CIA officer Andrew Bustamante.\n\nHe talks ...,1.698797e+09,None,NaN,NaN,NaN,None,1.752949e+09,MessageMediaDocument,1373.0,4.0,1.0,26.0,"{""\ud83d\udc4d"": 26}",file:///home/students/moliveira/telegram_2024/...,channel_1469309761
4,162996,NaN,NaN,1.698797e+09,None,NaN,NaN,NaN,None,1.752949e+09,MessageMediaPhoto,1507.0,4.0,1.0,29.0,"{""\ud83d\udd25"": 23, ""\ud83d\udc4f"": 5, ""\ud83...",file:///home/students/moliveira/telegram_2024/...,channel_1469309761
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82455528,6,NaN,/id,1.710090e+09,None,NaN,NaN,NaN,None,NaN,NaN,160.0,0.0,0.0,0.0,null,file:///home/students/moliveira/telegram_2024/...,channel_2050717976
82455529,609517172,NaN,False,NaN,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,file:///home/students/moliveira/telegram_2024/...,channel_2118959416
82455530,5187576451,NaN,False,NaN,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,file:///home/students/moliveira/telegram_2024/...,channel_2118959416
82455531,6641160034,NaN,False,NaN,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,file:///home/students/moliveira/telegram_2024/...,channel_1657715114
82455532,176365905,NaN,False,NaN,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,file:///home/students/moliveira/telegram_2024/...,channel_1645225394

In [6]:
df_graph = pd.read_parquet(DATA_DIR, columns = ["id", "user_id", "group_name"])
len(df_graph)

82455533

In [8]:
# 1. Dimensões Gerais
total_msgs = len(df_graph)
total_grupos = df_graph['group_name'].nunique()

# 2. Análise de Valores Nulos (Mensagens anónimas ou disparos de canais)
nulos_user_id = df_graph['user_id'].isna().sum()
pct_nulos = (nulos_user_id / total_msgs) * 100

# 3. Preparação para o Grafo (remover nulos, pois não formam arestas)
df_users = df_graph.dropna(subset=['user_id'])
total_users = df_users['user_id'].nunique()

# 4. Distribuição de Mensagens por Utilizador
msgs_por_user = df_users['user_id'].value_counts()

# 5. Comportamento de Coautoria (O motor do seu grafo)
# Conta em quantos grupos únicos cada utilizador publicou
grupos_por_user = df_users.groupby('user_id')['group_name'].nunique()

# Identifica os utilizadores "ponte" (que conectam 2 ou mais grupos)
users_multi_grupo = grupos_por_user[grupos_por_user > 1]
pct_multi_grupo = (len(users_multi_grupo) / total_users) * 100

print(f"--- ESTATÍSTICAS DA BASE ---")
print(f"Total de mensagens: {total_msgs:,}")
print(f"Total de grupos únicos: {total_grupos:,}")
print(f"Mensagens sem user_id (NaN): {nulos_user_id:,} ({pct_nulos:.2f}%)\n")

print(f"--- ESTATÍSTICAS DE UTILIZADORES ---")
print(f"Total de utilizadores únicos: {total_users:,}")
print(f"Média de mensagens por utilizador: {msgs_por_user.mean():.2f}")
print(f"Máximo de mensagens por um único utilizador: {msgs_por_user.max():,}\n")

print(f"--- POTENCIAL DO GRAFO (COAUTORIA) ---")
print(f"Utilizadores em apenas 1 grupo: {total_users - len(users_multi_grupo):,}")
print(f"Utilizadores em > 1 grupo (Pontes): {len(users_multi_grupo):,} ({pct_multi_grupo:.2f}%)")
print(f"Máximo de grupos frequentados por um único utilizador: {grupos_por_user.max()}")

--- ESTATÍSTICAS DA BASE ---
Total de mensagens: 82,455,533
Total de grupos únicos: 13,238
Mensagens sem user_id (NaN): 53,408,469 (64.77%)

--- ESTATÍSTICAS DE UTILIZADORES ---
Total de utilizadores únicos: 499,928
Média de mensagens por utilizador: 58.10
Máximo de mensagens por um único utilizador: 763,624

--- POTENCIAL DO GRAFO (COAUTORIA) ---
Utilizadores em apenas 1 grupo: 388,536
Utilizadores em > 1 grupo (Pontes): 111,392 (22.28%)
Máximo de grupos frequentados por um único utilizador: 415

In [1]:
import pandas as pd

df = pd.read_parquet("../data/processed/messages_preprocessed")
df

,id,group_name,text,timestamp,file_path,text_clean,datetime,language,date_type,clean_text,year,month
0,79832,channel_1683101758,@admin This account is threatening members,1698894032,file:///home/students/moliveira/telegram_2024/...,This account is threatening members,2023-11-02 03:00:32,en,2023-11-02 03:00:32,account threaten member,2023,11
1,95211,channel_1683101758,Most of the Gay porn search on google is made ...,1700613774,file:///home/students/moliveira/telegram_2024/...,Most of the Gay porn search on google is made ...,2023-11-22 00:42:54,en,2023-11-22 00:42:54,gay porn search google make pakistan happens s...,2023,11
2,205651,channel_1463755585,"Symbolism is everything , pig shagger Cameron ...",1699975266,file:///home/students/moliveira/telegram_2024/...,"Symbolism is everything , pig shagger Cameron ...",2023-11-14 15:21:06,en,2023-11-14 15:21:06,symbolism everything pig shagger cameron back ...,2023,11
3,208047,channel_1463755585,"""An emergent pandemic hit the world end of 201...",1701007810,file:///home/students/moliveira/telegram_2024/...,"""An emergent pandemic hit the world end of 201...",2023-11-26 14:10:10,en,2023-11-26 14:10:10,emergent pandemic hit world end destroy live c...,2023,11
4,87388,channel_1683101758,"I'm just saying what I would do, live and let ...",1699360132,file:///home/students/moliveira/telegram_2024/...,"I'm just saying what I would do, live and let ...",2023-11-07 12:28:52,en,2023-11-07 12:28:52,say would live let live long one harm anyone e...,2023,11
...,...,...,...,...,...,...,...,...,...,...,...,...
48425263,724,channel_2000341787,🦆 $DUCK Listing on OKX + AirDrop Announced! \...,1736441824,file:///home/students/moliveira/telegram_2024/...,🦆 $DUCK Listing on OKX + AirDrop Announced! \...,2025-01-09 16:57:04,en,2025-01-09 16:57:04,duck list okx airdrop announce ▪️okx listing d...,2025,1
48425264,809,channel_1648837346,2025/1/3 📈 \n\nToday's Newsletter & Twitter (P...,1735937527,file:///home/students/moliveira/telegram_2024/...,2025/1/3 📈 \n\nToday's Newsletter & Twitter (P...,2025-01-03 20:52:07,en,2025-01-03 20:52:07,today newsletter twitter please follow like th...,2025,1
48425265,618,channel_1930983957,"The world stands on a precipice, and the trend...",1736817377,file:///home/students/moliveira/telegram_2024/...,"The world stands on a precipice, and the trend...",2025-01-14 01:16:17,en,2025-01-14 01:16:17,world stand precipice trend good united state ...,2025,1
48425266,222,channel_2080462919,🧠 How to Use ChatGPT for SEO ?\n\nChatGPT is ...,1736419632,file:///home/students/moliveira/telegram_2024/...,🧠 How to Use ChatGPT for SEO ?\n\nChatGPT is ...,2025-01-09 10:47:12,en,2025-01-09 10:47:12,use chatgpt seo chatgpt powerful tool streamli...,2025,1
48425267,527,channel_2098876171,"The $5 to $10,000 Challenge Starts Now! \n\n-...",1736164400,file:///home/students/moliveira/telegram_2024/...,"The $5 to $10,000 Challenge Starts Now! \n\n-...",2025-01-06 11:53:20,en,2025-01-06 11:53:20,challenge start previous challenge smash goal ...,2025,1