In [11]:
import pandas as pd

df = pd.read_parquet("../data/processed/messages_with_language")

In [12]:
df

,id,group_name,text,timestamp,file_path,text_clean,datetime,language,year,month
0,2471233,channel_1698707268,Isn’t anyone talking yet about a blockade or o...,1699708879,file:///home/students/moliveira/telegram_2024/...,Isn’t anyone talking yet about a blockade or o...,2023-11-11 13:21:19,en,2023,11
1,2491481,channel_1698707268,Best meme since Bernie Sanders' mittens. It wi...,1700435904,file:///home/students/moliveira/telegram_2024/...,Best meme since Bernie Sanders' mittens. It wi...,2023-11-19 23:18:24,nl,2023,11
2,62462,channel_1851234959,One drop rule would mean people who get 0.01% ...,1699673884,file:///home/students/moliveira/telegram_2024/...,One drop rule would mean people who get 0.01% ...,2023-11-11 03:38:04,en,2023,11
3,69480,channel_1851234959,Reconquista happened and so it will happen again,1700436061,file:///home/students/moliveira/telegram_2024/...,Reconquista happened and so it will happen again,2023-11-19 23:21:01,en,2023,11
4,729382,channel_1522129471,Over your dead bodies,1700093043,file:///home/students/moliveira/telegram_2024/...,Over your dead bodies,2023-11-16 00:04:03,af,2023,11
...,...,...,...,...,...,...,...,...,...,...
5445,950728,channel_1370023850,🐆 with RABV. She self is inmmune but the one l...,1726578271,file:///home/students/moliveira/telegram_2024/...,🐆 with RABV. She self is inmmune but the one l...,2024-09-17 13:04:31,en,2024,9
5446,7840,channel_1653515977,JUST IN: 🚨 FTX will start repaying $16B to cre...,1725324522,file:///home/students/moliveira/telegram_2024/...,JUST IN: 🚨 FTX will start repaying $16B to cre...,2024-09-03 00:48:42,en,2024,9
5447,839415,channel_1887031669,In #Germany in Oktoberfest the man annoys Germ...,1727556976,file:///home/students/moliveira/telegram_2024/...,In #Germany in Oktoberfest the man annoys Germ...,2024-09-28 20:56:16,en,2024,9
5448,944034,channel_1370023850,"Hey Simion, how is that young family that pack...",1726035450,file:///home/students/moliveira/telegram_2024/...,"Hey Simion, how is that young family that pack...",2024-09-11 06:17:30,en,2024,9
5449,30361,channel_1919584255,Germany’s Silent Complicity: Funding Cuts Amid...,1736252410,file:///home/students/moliveira/telegram_2024/...,Germany’s Silent Complicity: Funding Cuts Amid...,2025-01-07 12:20:10,en,2025,1

In [13]:
df_en = df[df['language'] == 'en'].copy()
print(f"Número de mensagens em inglês: {len(df_en)}")

Número de mensagens em inglês: 5107

In [14]:
df_en.head(100)

,id,group_name,text,timestamp,file_path,text_clean,datetime,language,year,month
0,2471233,channel_1698707268,Isn’t anyone talking yet about a blockade or o...,1699708879,file:///home/students/moliveira/telegram_2024/...,Isn’t anyone talking yet about a blockade or o...,2023-11-11 13:21:19,en,2023,11
2,62462,channel_1851234959,One drop rule would mean people who get 0.01% ...,1699673884,file:///home/students/moliveira/telegram_2024/...,One drop rule would mean people who get 0.01% ...,2023-11-11 03:38:04,en,2023,11
3,69480,channel_1851234959,Reconquista happened and so it will happen again,1700436061,file:///home/students/moliveira/telegram_2024/...,Reconquista happened and so it will happen again,2023-11-19 23:21:01,en,2023,11
5,241328,channel_1526112366,The 248th Marine Corps Birthday Message: https...,1698995714,file:///home/students/moliveira/telegram_2024/...,The 248th Marine Corps Birthday Message:,2023-11-03 07:15:14,en,2023,11
6,317956,channel_1568299437,"Bald eagle, October 29, 2023, Brazoria County,...",1698861013,file:///home/students/moliveira/telegram_2024/...,"Bald eagle, October 29, 2023, Brazoria County,...",2023-11-01 17:50:13,en,2023,11
...,...,...,...,...,...,...,...,...,...,...
106,140910,channel_1409345080,Gript\nON THIS DAY: 15 NOVEMBER 1881: Birth of...,1700040111,file:///home/students/moliveira/telegram_2024/...,Gript\nON THIS DAY: 15 NOVEMBER 1881: Birth of...,2023-11-15 09:21:51,en,2023,11
107,131695,channel_1235779695,Thanks private Jewish bank.,1698862261,file:///home/students/moliveira/telegram_2024/...,Thanks private Jewish bank.,2023-11-01 18:11:01,en,2023,11
108,633570,channel_1202500264,"i have in the passed used tens machine , worke...",1699892624,file:///home/students/moliveira/telegram_2024/...,"i have in the passed used tens machine , worke...",2023-11-13 16:23:44,en,2023,11
109,465342,channel_1263412188,"MORE THAN 2,500 JOBS AT RISK IN LLOYDS SHAKE-U...",1700846798,file:///home/students/moliveira/telegram_2024/...,"MORE THAN 2,500 JOBS AT RISK IN LLOYDS SHAKE-U...",2023-11-24 17:26:38,en,2023,11
110,110495,channel_1161666782,"🇮🇱⚰️❗️ — On November 21, 2023, via its offici...",1700542761,file:///home/students/moliveira/telegram_2024/...,"🇮🇱⚰️❗️ — On November 21, 2023, via its offici...",2023-11-21 04:59:21,en,2023,11

In [15]:
df_nen = df[df['language'] != 'en'].copy()
print(f"Número de mensagens em outro idioma: {len(df_nen)}")

Número de mensagens em outro idioma: 343

In [16]:
df_nen.head(30)

,id,group_name,text,timestamp,file_path,text_clean,datetime,language,year,month
1,2491481,channel_1698707268,Best meme since Bernie Sanders' mittens. It wi...,1700435904,file:///home/students/moliveira/telegram_2024/...,Best meme since Bernie Sanders' mittens. It wi...,2023-11-19 23:18:24,nl,2023,11
4,729382,channel_1522129471,Over your dead bodies,1700093043,file:///home/students/moliveira/telegram_2024/...,Over your dead bodies,2023-11-16 00:04:03,af,2023,11
12,409599,channel_1595174369,Identifies as biden 🤣,1698999157,file:///home/students/moliveira/telegram_2024/...,Identifies as biden 🤣,2023-11-03 08:12:37,es,2023,11
60,56408,channel_1857065732,Look at Blinken... \n\n🤣🤣🤣 \n\nTwo Majors,1700079969,file:///home/students/moliveira/telegram_2024/...,Look at Blinken... \n\n🤣🤣🤣 \n\nTwo Majors,2023-11-15 20:26:09,af,2023,11
72,96111,channel_1438734111,2Pac - Eternal Thug (ft. Biggie) | 2023,1700414636,file:///home/students/moliveira/telegram_2024/...,2Pac - Eternal Thug (ft. Biggie) | 2023,2023-11-19 17:23:56,de,2023,11
76,113146,channel_1735249568,HODL \nTRUST IN THE PROJECT\nBE PATIENT\n💎🍀🔥🔥🔥🍀💎,1699893334,file:///home/students/moliveira/telegram_2024/...,HODL \nTRUST IN THE PROJECT\nBE PATIENT\n💎🍀🔥🔥🔥🍀💎,2023-11-13 16:35:34,vi,2023,11
80,14990,channel_1745006047,Hello tamu tamu available whatsapp upate saii ...,1700153549,file:///home/students/moliveira/telegram_2024/...,Hello tamu tamu available whatsapp upate saii ...,2023-11-16 16:52:29,et,2023,11
95,21091,channel_1813467025,If u can genuinely help.u r welcome.😔😔😔😭😭😭,1699628947,file:///home/students/moliveira/telegram_2024/...,If u can genuinely help.u r welcome.😔😔😔😭😭😭,2023-11-10 15:09:07,cy,2023,11
96,444,channel_1803107119,ULTRAVIOLET Sci-Fi FULL MOVIE,1701241410,file:///home/students/moliveira/telegram_2024/...,ULTRAVIOLET Sci-Fi FULL MOVIE,2023-11-29 07:03:30,it,2023,11
97,112719,channel_1758820844,👀Supervillain you say?\n\nhttps://t.me/JamesOK...,1700603296,file:///home/students/moliveira/telegram_2024/...,👀Supervillain you say?\n\n,2023-11-21 21:48:16,fi,2023,11
100,460483,channel_1263412188,BREAKING: 🇮🇱 IDF GROUND OPERATION DEATH TOLL R...,1699505697,file:///home/students/moliveira/telegram_2024/...,BREAKING: 🇮🇱 IDF GROUND OPERATION DEATH TOLL R...,2023-11-09 04:54:57,de,2023,11
117,463895,channel_1263412188,"ALTMAN, BROCKMAN WILL BE JOINING MICROSOFT: NA...",1700467199,file:///home/students/moliveira/telegram_2024/...,"ALTMAN, BROCKMAN WILL BE JOINING MICROSOFT: NA...",2023-11-20 07:59:59,so,2023,11
120,92390,channel_1458759868,"Es ist besser etwas zu erschaffen, das andere ...",1699913428,file:///home/students/moliveira/telegram_2024/...,"Es ist besser etwas zu erschaffen, das andere ...",2023-11-13 22:10:28,de,2023,11
136,425166,channel_1441246337,I keep forgetting I’m getting older too lol,1700082308,file:///home/students/moliveira/telegram_2024/...,I keep forgetting I’m getting older too lol,2023-11-15 21:05:08,no,2023,11
156,81337,channel_1683101758,People felt liberated,1698962704,file:///home/students/moliveira/telegram_2024/...,People felt liberated,2023-11-02 22:05:04,da,2023,11
185,1073400,channel_1556404753,🔴💣CAUSE IGNOTE HANNO PORTATO UN BUS A SCHIANTA...,1700337192,file:///home/students/moliveira/telegram_2024/...,🔴💣CAUSE IGNOTE HANNO PORTATO UN BUS A SCHIANTA...,2023-11-18 19:53:12,it,2023,11
197,7482,channel_1643755063,🔥 STUNNING CREATURES ☕️\n\n#animals,1698909916,file:///home/students/moliveira/telegram_2024/...,🔥 STUNNING CREATURES ☕️\n\n#animals,2023-11-02 07:25:16,tl,2023,11
237,106383,channel_1700320039,Hickory Smoked Nigger 🤣,1699559732,file:///home/students/moliveira/telegram_2024/...,Hickory Smoked Nigger 🤣,2023-11-09 19:55:32,da,2023,11
238,14019,channel_1227682995,Работино и Бредли это две несовместимые вещи...,1700499224,file:///home/students/moliveira/telegram_2024/...,Работино и Бредли это две несовместимые вещи...,2023-11-20 16:53:44,ru,2023,11
248,347537,channel_1301697336,https://t.me/ugofuoco/3426 🔴💣MEDIA TERRORISTI...,1699913424,file:///home/students/moliveira/telegram_2024/...,🔴💣MEDIA TERRORISTI. L'EUROPARLAMENTARE CROAT...,2023-11-13 22:10:24,it,2023,11
266,48189,channel_1623527278,"Heavy metals, fetal cells, can'cercells, cells...",1701027217,file:///home/students/moliveira/telegram_2024/...,"Heavy metals, fetal cells, can'cercells, cells...",2023-11-26 19:33:37,ca,2023,11
267,269706,channel_1671860401,An you chek you got my usdt \n1003,1699077706,file:///home/students/moliveira/telegram_2024/...,An you chek you got my usdt \n1003,2023-11-04 06:01:46,cs,2023,11
268,122091,channel_1904302842,Daddy daddy I’m coming,1700040223,file:///home/students/moliveira/telegram_2024/...,Daddy daddy I’m coming,2023-11-15 09:23:43,cy,2023,11
283,947125,channel_1791839714,ab yha bhi chori krne lge tumlog,1700740757,file:///home/students/moliveira/telegram_2024/...,ab yha bhi chori krne lge tumlog,2023-11-23 11:59:17,et,2023,11
294,792,channel_1228507102,Good night 🍀💫\n\nNATION DEGRADATION,1700947170,file:///home/students/moliveira/telegram_2024/...,Good night 🍀💫\n\nNATION DEGRADATION,2023-11-25 21:19:30,af,2023,11
303,75404,channel_1420727748,🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠\n\nИщете страхового брокера?\n...,1699613922,file:///home/students/moliveira/telegram_2024/...,🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠\n\nИщете страхового брокера?\n...,2023-11-10 10:58:42,ru,2023,11
355,342252,channel_1568299437,Too friggin funny😂 woopsie,1702579118,file:///home/students/moliveira/telegram_2024/...,Too friggin funny😂 woopsie,2023-12-14 18:38:38,af,2023,12
357,5367,channel_1254327265,بسم الله نبدأ\nعروض cmd technology 🔥\n\n❌ جماع...,1702230505,file:///home/students/moliveira/telegram_2024/...,بسم الله نبدأ\nعروض cmd technology 🔥\n\n❌ جماع...,2023-12-10 17:48:25,ar,2023,12
363,1018662,channel_1365527742,Or wo bhi har bar paise badte jayga 3000 per m...,1701877346,file:///home/students/moliveira/telegram_2024/...,Or wo bhi har bar paise badte jayga 3000 per m...,2023-12-06 15:42:26,id,2023,12
377,330134,channel_1671860401,Ajj kaafi din baad Live Daytrading kitti mai t...,1703838673,file:///home/students/moliveira/telegram_2024/...,Ajj kaafi din baad Live Daytrading kitti mai t...,2023-12-29 08:31:13,et,2023,12

In [17]:
df.to_csv("../reports/sample_test_english.csv")